//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK_Easybar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador_bar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public administrador_bar()
        {
            this.bar = new HashSet<bar>();
        }
    
        public int id_admin { get; set; }
        public int id_rol { get; set; }
        public int cedula_a { get; set; }
        public string nombre_completo_a { get; set; }
        public string correo_a { get; set; }
        public string Telefono_a { get; set; }
        public string contraseña_a { get; set; }
        public System.DateTime fecha_adicion_a { get; set; }
        public bool estado_admin { get; set; }
    
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bar> bar { get; set; }
    }
}
