//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK_Easybar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bar()
        {
            this.Pedidos = new HashSet<Pedidos>();
            this.producto = new HashSet<producto>();
            this.publicidad = new HashSet<publicidad>();
        }
    
        public int id_bar { get; set; }
        public int id_admin { get; set; }
        public string nit_bar { get; set; }
        public string nombre_bar { get; set; }
        public string Direccion_bar { get; set; }
        public string Telefono_bar1 { get; set; }
        public string Telefono_bar2 { get; set; }
        public string Logo_bar { get; set; }
        public string link_washap { get; set; }
        public string link_facebook { get; set; }
        public string link_instagram { get; set; }
        public string correo_b { get; set; }
        public bool estado_bar { get; set; }
        public string Horario { get; set; }
        public System.DateTime fecha_adicion { get; set; }
    
        public virtual administrador_bar administrador_bar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<publicidad> publicidad { get; set; }
    }
}
