//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK_Easybar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_easybarEntities : DbContext
    {
        public db_easybarEntities()
            : base("name=db_easybarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrador_bar> administrador_bar { get; set; }
        public virtual DbSet<bar> bar { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<publicidad> publicidad { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
    }
}
