//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK_Easybar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int id_cliente { get; set; }
        public int id_rol { get; set; }
        public int cedula { get; set; }
        public string nombre_completo { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public string Barrio_localidad { get; set; }
        public string Telefono { get; set; }
        public string contraseña { get; set; }
        public System.DateTime fecha_adicion { get; set; }
        public bool estado_cliente { get; set; }
    
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
