//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK_Easybar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int id_pedido { get; set; }
        public int id_cliente { get; set; }
        public int id_bar { get; set; }
        public decimal valor_pedido { get; set; }
        public bool estado_pedido { get; set; }
        public string descripcion_pedido { get; set; }
    
        public virtual bar bar { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
