//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK_Easybar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicidad
    {
        public int id_publicidad { get; set; }
        public int id_bar { get; set; }
        public string nombre_publicidad { get; set; }
        public string tiempo_publicidad { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> valor { get; set; }
        public string Imagen_publicidad { get; set; }
        public bool Estado_publicidad { get; set; }
    
        public virtual bar bar { get; set; }
    }
}
